### ISSUE TITLE
Find where notification messages are hardcoded in Spanish + add trans

### ISSUE THREAD

**Issue by johnny2smooth** [uwcirg/tb-foundation#139]
Kyle solved on back end.

Note from Kyle regarding this issue: 

All of the notification translations are handled on the backend since that is where they are sent from. I tried to move this to the frontend but it was really complicated because you can’t check what language the user has selected from the serviceworker ( serviceworker cant access localstorage and stuff )

The backend translation files live here and arent currently synced to Transifex
https://github.com/uwcirg/tb-foundation/tree/develop/config/locales

There is a hash here that stores the various types of notifications that we use throughout the app to keep them consistent
https://github.com/uwcirg/tb-foundation/blob/develop/app/lib/notification_definitions.rb
In the codebase it mostly looks like
`NotifyUser.new(user_object).type_of_notification_to_send`

NotifyUser handles the translation based on the Users locale ( users table, locale column )
https://github.com/uwcirg/tb-foundation/blob/develop/app/services/notify_user.rb

The rest of the code in that class basically checks the notifications_definitions.rb file I linked above, and gets the relevant strings / links / icons and stuff from that hash for the specific type of notification we are sending

**Comment by kylegoodwin** [comment]
I think we determined this is not needed right? It was the users configuration

**Comment by johnny2smooth** [comment]
@kylegoodwin yea, I'm pretty sure that you're right
